[project]
name = "demo-repo"
version = "0.4.0"
requires-python = ">=3.12, <3.14"
dependencies = [
    "cocotb",
    "cocotb-bus",
    "pike-type",
    "pytest",
]

[project.optional-dependencies]
dev = [
    "pytest-xdist",
    "cocotb-test",
]

[tool.uv.sources]
pike-type = { path = "../pike-type", editable = true }
