# Generated by piketype
# Source: alpha/piketype/bar.py
# Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass, field

from alpha.py.foo_types import byte_ct

@dataclass
class bar_ct:
    WIDTH = 16
    BYTE_COUNT = 2
    field1: byte_ct = field(default_factory=byte_ct)
    field2: byte_ct = field(default_factory=byte_ct)

    def __setattr__(self, name: str, value: object) -> None:
        if name == "field1":
            value = self._coerce_field1(value)
        elif name == "field2":
            value = self._coerce_field2(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_field1(value: object) -> byte_ct:
        if isinstance(value, byte_ct):
            return value
        return byte_ct(value)

    @staticmethod
    def _coerce_field2(value: object) -> byte_ct:
        if isinstance(value, byte_ct):
            return value
        return byte_ct(value)

    def to_bytes(self) -> bytes:
        result = bytearray()
        result.extend(self.field1.to_bytes())
        result.extend(self.field2.to_bytes())
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "bar_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("bar_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("bar_ct.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.field1 = byte_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        obj.field2 = byte_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        return obj

    def clone(self) -> "bar_ct":
        return type(self).from_bytes(self.to_bytes())
