# Generated by piketype
# Source: alpha/piketype/bar.py
# Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass, field

from .foo_types import byte_ct

@dataclass
class bar_ct:
    WIDTH = 16
    BYTE_COUNT = 2
    field1: byte_ct = field(default_factory=byte_ct)
    field2: byte_ct = field(default_factory=byte_ct)

    def __setattr__(self, name: str, value: object) -> None:
        if name == "field1":
            value = self._coerce_field1(value)
        elif name == "field2":
            value = self._coerce_field2(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_field1(value: object) -> byte_ct:
        if isinstance(value, byte_ct):
            return value
        return byte_ct(value)

    @staticmethod
    def _coerce_field2(value: object) -> byte_ct:
        if isinstance(value, byte_ct):
            return value
        return byte_ct(value)

    def pack(self) -> int:
        result = 0
        result = (result << 8) | self.field1.pack()
        result = (result << 8) | self.field2.pack()
        return result

    @classmethod
    def unpack(cls, packed: int) -> "bar_ct":
        obj = cls()
        obj.field1 = byte_ct.unpack((packed >> 8) & 255)
        obj.field2 = byte_ct.unpack((packed >> 0) & 255)
        return obj

    def to_lv(self) -> int:
        return int.from_bytes(self.to_bytes(), "big", signed=False)

    @classmethod
    def from_lv(cls, value: int) -> "bar_ct":
        return cls.from_bytes((value & ((1 << (cls.BYTE_COUNT * 8)) - 1)).to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        result = bytearray()
        result.extend(self.field1.to_bytes())
        result.extend(self.field2.to_bytes())
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "bar_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("bar_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("bar_ct.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.field1 = byte_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        obj.field2 = byte_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        return obj

    def clone(self) -> "bar_ct":
        return type(self).from_bytes(self.to_bytes())

    def compare(self, other: object, msg: str = "") -> None:
        assert isinstance(other, bar_ct), "Expected bar_ct, got " + str(type(other))
        diffs = []
        if self.field1 != other.field1:
            diffs.append("field1: expected {!r}, got {!r}".format(self.field1, other.field1))
        if self.field2 != other.field2:
            diffs.append("field2: expected {!r}, got {!r}".format(self.field2, other.field2))
        if diffs:
            prefix = msg + ": " if msg else ""
            raise AssertionError(prefix + repr(self) + " != " + repr(other) + " — " + ", ".join(diffs))
