# Generated by piketype
# Source: alpha/piketype/constants.py
# Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass, field

from enum import IntEnum

FOO = 100000
BAR = 0
A = 3
B = (A + 5)
C = ((A << 2) | 1)
D = (-A)
E = (~A)
W = 13
F = 3
G = 0x0C
H = 0xC

class addr_ct:
    WIDTH = 13
    SIGNED = False
    BYTE_COUNT = 2
    MIN_VALUE = 0
    MAX_VALUE = 8191

    def __init__(self, value: int = 0) -> None:
        if not isinstance(value, int):
            raise TypeError("addr_ct value must be int")
        if value < self.MIN_VALUE or value > self.MAX_VALUE:
            raise ValueError("addr_ct value out of range")
        self.value = value

    def _to_packed_int(self) -> int:
        return self.value

    @classmethod
    def _from_packed_int(cls, packed: int) -> "addr_ct":
        return cls(packed)

    def to_bytes(self) -> bytes:
        return self.value.to_bytes(self.BYTE_COUNT, "big", signed=False)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "addr_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("addr_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("addr_ct.from_bytes size mismatch")
        value = int.from_bytes(raw, "big", signed=False) & cls.MAX_VALUE
        return cls(value)

    def clone(self) -> "addr_ct":
        return type(self)(self.value)

    def __int__(self) -> int:
        return self.value

    def __index__(self) -> int:
        return self.value

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, int):
            return self.value == other
        return NotImplemented

    def __repr__(self) -> str:
        return f"addr_ct(value={self.value!r})"

class mask_ct:
    WIDTH = 8
    SIGNED = True
    BYTE_COUNT = 1
    MIN_VALUE = -128
    MAX_VALUE = 127
    MASK = 255
    SIGN_BIT = 128

    def __init__(self, value: int = 0) -> None:
        if not isinstance(value, int):
            raise TypeError("mask_ct value must be int")
        if value < self.MIN_VALUE or value > self.MAX_VALUE:
            raise ValueError("mask_ct value out of range")
        self.value = value

    def _to_packed_int(self) -> int:
        return self.value & self.MASK

    @classmethod
    def _from_packed_int(cls, packed: int) -> "mask_ct":
        value = packed & cls.MASK
        signed_value = value - (1 << cls.WIDTH) if (value & cls.SIGN_BIT) else value
        return cls(signed_value)

    def to_bytes(self) -> bytes:
        mask = self.MASK
        packed = self.value & mask
        if self.value < 0:
            packed |= ((1 << (self.BYTE_COUNT * 8)) - 1) ^ mask
        return packed.to_bytes(self.BYTE_COUNT, "big", signed=False)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "mask_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("mask_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("mask_ct.from_bytes size mismatch")
        raw_int = int.from_bytes(raw, "big", signed=False)
        data_bits = raw_int & cls.MASK
        padding = raw_int >> cls.WIDTH
        sign_bit = (data_bits >> (cls.WIDTH - 1)) & 1
        expected_padding = ((1 << 0) - 1) if sign_bit else 0
        if padding != expected_padding:
            raise ValueError("mask_ct.from_bytes signed padding mismatch")
        return cls._from_packed_int(data_bits)

    def clone(self) -> "mask_ct":
        return type(self)(self.value)

    def __int__(self) -> int:
        return self.value

    def __index__(self) -> int:
        return self.value

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, int):
            return self.value == other
        return NotImplemented

    def __repr__(self) -> str:
        return f"mask_ct(value={self.value!r})"

class flag_ct:
    WIDTH = 1
    SIGNED = False
    BYTE_COUNT = 1
    MIN_VALUE = 0
    MAX_VALUE = 1

    def __init__(self, value: int = 0) -> None:
        if not isinstance(value, int):
            raise TypeError("flag_ct value must be int")
        if value < self.MIN_VALUE or value > self.MAX_VALUE:
            raise ValueError("flag_ct value out of range")
        self.value = value

    def _to_packed_int(self) -> int:
        return self.value

    @classmethod
    def _from_packed_int(cls, packed: int) -> "flag_ct":
        return cls(packed)

    def to_bytes(self) -> bytes:
        return self.value.to_bytes(self.BYTE_COUNT, "big", signed=False)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "flag_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("flag_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("flag_ct.from_bytes size mismatch")
        value = int.from_bytes(raw, "big", signed=False) & cls.MAX_VALUE
        return cls(value)

    def clone(self) -> "flag_ct":
        return type(self)(self.value)

    def __int__(self) -> int:
        return self.value

    def __index__(self) -> int:
        return self.value

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, int):
            return self.value == other
        return NotImplemented

    def __repr__(self) -> str:
        return f"flag_ct(value={self.value!r})"

class big_data_ct:
    WIDTH = 67
    SIGNED = False
    BYTE_COUNT = 9
    MAX_VALUE = 147573952589676412927

    def __init__(self, value: bytes | bytearray | int = b'') -> None:
        if isinstance(value, int):
            if value < 0 or value > self.MAX_VALUE:
                raise ValueError("big_data_ct value out of range")
            self.value = value.to_bytes(self.BYTE_COUNT, "big", signed=False)
            return
        if not isinstance(value, (bytes, bytearray)):
            raise TypeError("big_data_ct value must be bytes, bytearray, or int")
        raw = bytes(value)
        if len(raw) == 0:
            raw = b"\x00" * self.BYTE_COUNT
        if len(raw) != self.BYTE_COUNT:
            raise ValueError("big_data_ct value size mismatch")
        self.value = raw

    def _to_packed_int(self) -> int:
        return int.from_bytes(self.value, "big", signed=False)

    @classmethod
    def _from_packed_int(cls, packed: int) -> "big_data_ct":
        return cls(packed.to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        return self.value

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "big_data_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("big_data_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("big_data_ct.from_bytes size mismatch")
        # Mask padding bits in MSB byte
        masked = bytes([raw[0] & 7]) + raw[1:]
        return cls(masked)

    def clone(self) -> "big_data_ct":
        return type(self)(self.value)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, (bytes, bytearray)):
            return self.value == bytes(other)
        return NotImplemented

    def __repr__(self) -> str:
        return f"big_data_ct(value={self.value!r})"

class status_enum_t(IntEnum):
    OK = 0
    ERROR = 1
    TIMEOUT = 2
    UNKNOWN = 3
    INVALID = 4

class status_ct:
    WIDTH = 3
    BYTE_COUNT = 1

    def __init__(self, value: status_enum_t = status_enum_t.OK) -> None:
        if not isinstance(value, status_enum_t):
            raise TypeError("status_ct value must be status_enum_t")
        self.value = value

    def to_bytes(self) -> bytes:
        return int(self.value).to_bytes(1, "big", signed=False)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "status_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("status_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != 1:
            raise ValueError("status_ct.from_bytes size mismatch")
        raw_int = int.from_bytes(raw, "big", signed=False) & 7
        try:
            enum_val = status_enum_t(raw_int)
        except ValueError:
            raise ValueError("status_ct.from_bytes unknown enum value")
        return cls(enum_val)

    def clone(self) -> "status_ct":
        return type(self)(self.value)

    def __int__(self) -> int:
        return int(self.value)

    def __index__(self) -> int:
        return int(self.value)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, int):
            return int(self.value) == other
        return NotImplemented

    def __repr__(self) -> str:
        return f"status_ct(value={self.value!r})"

class flags_ct:
    WIDTH: int = 3
    BYTE_COUNT: int = 1

    def __init__(self) -> None:
        self._value: int = 0

    @property
    def invalid_data(self) -> bool:
        return (self._value & 128) != 0

    @invalid_data.setter
    def invalid_data(self, v: bool) -> None:
        if v:
            self._value |= 128
        else:
            self._value &= ~128

    @property
    def timeout(self) -> bool:
        return (self._value & 64) != 0

    @timeout.setter
    def timeout(self, v: bool) -> None:
        if v:
            self._value |= 64
        else:
            self._value &= ~64

    @property
    def overflow(self) -> bool:
        return (self._value & 32) != 0

    @overflow.setter
    def overflow(self, v: bool) -> None:
        if v:
            self._value |= 32
        else:
            self._value &= ~32

    def to_bytes(self) -> bytes:
        return (self._value & 224).to_bytes(1, "big")

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "flags_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("flags_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != 1:
            raise ValueError("flags_ct.from_bytes size mismatch")
        obj = cls()
        obj._value = int.from_bytes(raw, "big") & 224
        return obj

    def clone(self) -> "flags_ct":
        obj = self.__class__()
        obj._value = self._value & 224
        return obj

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, flags_ct):
            return NotImplemented
        return (self._value & 224) == (other._value & 224)

@dataclass
class header_ct:
    WIDTH = 84
    BYTE_COUNT = 13
    addr: addr_ct = field(default_factory=addr_ct)
    enable: flag_ct = field(default_factory=flag_ct)
    data: big_data_ct = field(default_factory=big_data_ct)
    status: flags_ct = field(default_factory=flags_ct)

    def __setattr__(self, name: str, value: object) -> None:
        if name == "addr":
            value = self._coerce_addr(value)
        elif name == "enable":
            value = self._coerce_enable(value)
        elif name == "data":
            value = self._coerce_data(value)
        elif name == "status":
            value = self._coerce_status(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_addr(value: object) -> addr_ct:
        if isinstance(value, addr_ct):
            return value
        return addr_ct(value)

    @staticmethod
    def _coerce_enable(value: object) -> flag_ct:
        if isinstance(value, flag_ct):
            return value
        return flag_ct(value)

    @staticmethod
    def _coerce_data(value: object) -> big_data_ct:
        if isinstance(value, big_data_ct):
            return value
        return big_data_ct(value)

    @staticmethod
    def _coerce_status(value: object) -> flags_ct:
        if isinstance(value, flags_ct):
            return value
        raise TypeError("header_ct.status must be flags_ct")

    def to_bytes(self) -> bytes:
        result = bytearray()
        result.extend(self.addr.to_bytes())
        result.extend(self.enable.to_bytes())
        result.extend(self.data.to_bytes())
        result.extend(self.status.to_bytes())
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "header_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("header_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("header_ct.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.addr = addr_ct.from_bytes(raw[offset:offset + 2])
        offset += 2
        obj.enable = flag_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        obj.data = big_data_ct.from_bytes(raw[offset:offset + 9])
        offset += 9
        obj.status = flags_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        return obj

    def clone(self) -> "header_ct":
        return type(self).from_bytes(self.to_bytes())

@dataclass
class packet_ct:
    WIDTH = 156
    BYTE_COUNT = 24
    header: header_ct | None = field(default_factory=header_ct)
    status: status_ct = field(default_factory=status_ct)
    mode: int = 0
    error_code: int = 0
    data1: int = 0
    data2: int = 0

    def __setattr__(self, name: str, value: object) -> None:
        if name == "header":
            value = self._coerce_header(value)
        elif name == "status":
            value = self._coerce_status(value)
        elif name == "mode":
            value = self._coerce_mode(value)
        elif name == "error_code":
            value = self._coerce_error_code(value)
        elif name == "data1":
            value = self._coerce_data1(value)
        elif name == "data2":
            value = self._coerce_data2(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_header(value: object) -> header_ct | None:
        if value is None:
            return None
        if isinstance(value, header_ct):
            return value
        raise TypeError("packet_ct.header must be header_ct or None")

    @staticmethod
    def _coerce_status(value: object) -> status_ct:
        if isinstance(value, status_ct):
            return value
        raise TypeError("packet_ct.status must be status_ct")

    @staticmethod
    def _coerce_mode(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("packet_ct.mode must be int")
        if value < 0 or value > 3:
            raise ValueError("packet_ct.mode value out of range")
        return value

    @staticmethod
    def _coerce_error_code(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("packet_ct.error_code must be int")
        if value < 0 or value > 7:
            raise ValueError("packet_ct.error_code value out of range")
        return value

    @staticmethod
    def _coerce_data1(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("packet_ct.data1 must be int")
        if value < -2147483648 or value > 2147483647:
            raise ValueError("packet_ct.data1 value out of range")
        return value

    @staticmethod
    def _coerce_data2(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("packet_ct.data2 must be int")
        if value < 0 or value > 4294967295:
            raise ValueError("packet_ct.data2 value out of range")
        return value

    def to_bytes(self) -> bytes:
        result = bytearray()
        if self.header is None:
            raise ValueError("header cannot be None during packing")
        result.extend(self.header.to_bytes())
        result.extend(self.status.to_bytes())
        _packed_mode = self.mode & 3
        result.extend(_packed_mode.to_bytes(1, "big", signed=False))
        _packed_error_code = self.error_code & 7
        result.extend(_packed_error_code.to_bytes(1, "big", signed=False))
        _mask_data1 = 4294967295
        _packed_data1 = self.data1 & _mask_data1
        if self.data1 < 0:
            _packed_data1 |= ((1 << 32) - 1) ^ _mask_data1
        result.extend(_packed_data1.to_bytes(4, "big", signed=False))
        _packed_data2 = self.data2 & 4294967295
        result.extend(_packed_data2.to_bytes(4, "big", signed=False))
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "packet_ct":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("packet_ct.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("packet_ct.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.header = header_ct.from_bytes(raw[offset:offset + 13])
        offset += 13
        obj.status = status_ct.from_bytes(raw[offset:offset + 1])
        offset += 1
        obj.mode = int.from_bytes(raw[offset:offset + 1], "big", signed=False) & 3
        offset += 1
        obj.error_code = int.from_bytes(raw[offset:offset + 1], "big", signed=False) & 7
        offset += 1
        _raw_int_data1 = int.from_bytes(raw[offset:offset + 4], "big", signed=False)
        _data_data1 = _raw_int_data1 & 4294967295
        _padding_data1 = _raw_int_data1 >> 32
        _sign_bit_data1 = (_data_data1 >> 31) & 1
        _expected_padding_data1 = ((1 << 0) - 1) if _sign_bit_data1 else 0
        if _padding_data1 != _expected_padding_data1:
            raise ValueError("packet_ct.from_bytes signed padding mismatch for data1")
        obj.data1 = _data_data1 - 4294967296 if (_data_data1 & 2147483648) else _data_data1
        offset += 4
        obj.data2 = int.from_bytes(raw[offset:offset + 4], "big", signed=False) & 4294967295
        offset += 4
        return obj

    def clone(self) -> "packet_ct":
        return type(self).from_bytes(self.to_bytes())
