// Generated by piketype
// Source: alpha/piketype/foo.py
// Do not edit by hand.

package foo_test_pkg;
  import foo_pkg::*;

  class byte_ct;
    localparam int WIDTH = LP_BYTE_WIDTH;
    localparam int BYTE_COUNT = LP_BYTE_BYTE_COUNT;
    rand byte_t value;
  
    function new(byte_t value_in = '0);
      value = value_in;
    endfunction
  
    function automatic byte_t to_slv();
      return value;
    endfunction
  
    function void from_slv(byte_t value_in);
      value = value_in;
    endfunction
  
    task automatic to_bytes(output byte unsigned bytes[]);
      logic [7:0] padded;
      bytes = new[BYTE_COUNT];
      padded = '0;
      padded[WIDTH-1:0] = value;
      for (int idx = 0; idx < BYTE_COUNT; idx++) begin
        bytes[idx] = padded[(BYTE_COUNT - 1 - idx)*8 +: 8];
      end
    endtask
  
    function void from_bytes(input byte unsigned bytes[]);
      logic [7:0] padded;
      if (bytes.size() != BYTE_COUNT) begin
        $fatal(1, "byte_ct.from_bytes size mismatch: expected %0d got %0d", BYTE_COUNT, bytes.size());
      end
      padded = '0;
      for (int idx = 0; idx < BYTE_COUNT; idx++) begin
        padded[(BYTE_COUNT - 1 - idx)*8 +: 8] = bytes[idx];
      end
      value = byte_t'(padded[WIDTH-1:0]);
    endfunction
  
    function void copy(input byte_ct rhs);
      value = rhs.value;
    endfunction
  
    function automatic byte_ct clone();
      byte_ct cloned = new();
      cloned.value = value;
      return cloned;
    endfunction
  
    function automatic bit compare(input byte_ct rhs);
      return value === rhs.value;
    endfunction
  
    function automatic string sprint();
      return $sformatf("byte_ct(value=0x%0h)", value);
    endfunction
  endclass : byte_ct
endpackage
