// Generated by piketype
// Source: alpha/piketype/bar.py
// Do not edit by hand.

package bar_pkg;
  import foo_pkg::LP_BYTE_WIDTH;
  import foo_pkg::byte_t;
  import foo_pkg::pack_byte;
  import foo_pkg::unpack_byte;

  localparam int LP_BAR_WIDTH = 16;
  localparam int LP_BAR_BYTE_COUNT = 2;

  typedef struct packed {
    byte_t field1;
    byte_t field2;
  } bar_t;

  function automatic logic [LP_BAR_WIDTH-1:0] pack_bar(bar_t a);
    return {pack_byte(a.field1), pack_byte(a.field2)};
  endfunction

  function automatic bar_t unpack_bar(logic [LP_BAR_WIDTH-1:0] a);
    bar_t result;
    result = '0;
    result.field2 = unpack_byte(a[7:0]);
    result.field1 = unpack_byte(a[15:8]);
    return result;
  endfunction
endpackage
