// Generated by piketype
// Source: alpha/piketype/constants.py
// Do not edit by hand.

package constants_pkg;

  localparam longint FOO = 64'sd100000;
  localparam int unsigned BAR = 32'd0;
  localparam int unsigned A = 32'd3;
  localparam int B = (A + 5);
  localparam int C = ((A << 2) | 1);
  localparam int D = (-A);
  localparam int E = (~A);
  localparam int W = 32'sd13;
  localparam logic [4:0] F = 5'd3;
  localparam logic [4:0] G = 5'h0C;
  localparam logic [3:0] H = 4'hC;

  localparam int LP_ADDR_WIDTH = W;
  localparam int LP_ADDR_BYTE_COUNT = 2;

  typedef bit [LP_ADDR_WIDTH-1:0] addr_t;

  function automatic logic [LP_ADDR_WIDTH-1:0] pack_addr(addr_t a);
    return a;
  endfunction

  function automatic addr_t unpack_addr(logic [LP_ADDR_WIDTH-1:0] a);
    return a;
  endfunction

  localparam int LP_MASK_WIDTH = 8;
  localparam int LP_MASK_BYTE_COUNT = 1;

  typedef logic signed [LP_MASK_WIDTH-1:0] mask_t;

  function automatic logic [LP_MASK_WIDTH-1:0] pack_mask(mask_t a);
    return a;
  endfunction

  function automatic mask_t unpack_mask(logic [LP_MASK_WIDTH-1:0] a);
    return signed'(a);
  endfunction

  localparam int LP_FLAG_WIDTH = 1;
  localparam int LP_FLAG_BYTE_COUNT = 1;

  typedef bit flag_t;

  function automatic logic [LP_FLAG_WIDTH-1:0] pack_flag(flag_t a);
    return a;
  endfunction

  function automatic flag_t unpack_flag(logic [LP_FLAG_WIDTH-1:0] a);
    return a;
  endfunction

  localparam int LP_BIG_DATA_WIDTH = 67;
  localparam int LP_BIG_DATA_BYTE_COUNT = 9;

  typedef bit [LP_BIG_DATA_WIDTH-1:0] big_data_t;

  function automatic logic [LP_BIG_DATA_WIDTH-1:0] pack_big_data(big_data_t a);
    return a;
  endfunction

  function automatic big_data_t unpack_big_data(logic [LP_BIG_DATA_WIDTH-1:0] a);
    return a;
  endfunction

  localparam int LP_STATUS_WIDTH = 3;
  localparam int LP_STATUS_BYTE_COUNT = 1;

  typedef enum logic [LP_STATUS_WIDTH-1:0] {OK = 0, ERROR = 1, TIMEOUT = 2, UNKNOWN = 3, INVALID = 4} status_t;

  function automatic logic [LP_STATUS_WIDTH-1:0] pack_status(status_t a);
    return LP_STATUS_WIDTH'(a);
  endfunction

  function automatic status_t unpack_status(logic [LP_STATUS_WIDTH-1:0] a);
    return status_t'(a);
  endfunction

  localparam int LP_FLAGS_WIDTH = 3;
  localparam int LP_FLAGS_BYTE_COUNT = 1;

  typedef struct packed {
    logic invalid_data;
    logic timeout;
    logic overflow;
    logic [4:0] _align_pad;
  } flags_t;

  function automatic logic [LP_FLAGS_WIDTH-1:0] pack_flags(flags_t a);
    return {a.invalid_data, a.timeout, a.overflow};
  endfunction

  function automatic flags_t unpack_flags(logic [LP_FLAGS_WIDTH-1:0] a);
    flags_t result;
    result = '0;
    result.overflow = a[0];
    result.timeout = a[1];
    result.invalid_data = a[2];
    return result;
  endfunction

  localparam int LP_HEADER_WIDTH = 84;
  localparam int LP_HEADER_BYTE_COUNT = 13;

  typedef struct packed {
    logic [2:0] addr_pad;
    addr_t addr;
    logic [6:0] enable_pad;
    flag_t enable;
    logic [4:0] data_pad;
    big_data_t data;
    flags_t status;
  } header_t;

  function automatic logic [LP_HEADER_WIDTH-1:0] pack_header(header_t a);
    return {pack_addr(a.addr), pack_flag(a.enable), pack_big_data(a.data), pack_flags(a.status)};
  endfunction

  function automatic header_t unpack_header(logic [LP_HEADER_WIDTH-1:0] a);
    header_t result;
    result = '0;
    result.status = unpack_flags(a[2:0]);
    result.data = unpack_big_data(a[69:3]);
    result.enable = unpack_flag(a[70:70]);
    result.addr = unpack_addr(a[83:71]);
    return result;
  endfunction

  localparam int LP_PACKET_WIDTH = 156;
  localparam int LP_PACKET_BYTE_COUNT = 24;

  typedef struct packed {
    header_t header;
    logic [4:0] status_pad;
    status_t status;
    logic [5:0] mode_pad;
    logic [1:0] mode;
    logic [4:0] error_code_pad;
    bit [2:0] error_code;
    logic signed [31:0] data1;
    logic [31:0] data2;
  } packet_t;

  function automatic logic [LP_PACKET_WIDTH-1:0] pack_packet(packet_t a);
    return {pack_header(a.header), pack_status(a.status), a.mode, a.error_code, a.data1, a.data2};
  endfunction

  function automatic packet_t unpack_packet(logic [LP_PACKET_WIDTH-1:0] a);
    packet_t result;
    result = '0;
    result.data2 = a[31:0];
    result.data1 = signed'(a[63:32]);
    result.error_code = a[66:64];
    result.mode = a[68:67];
    result.status = unpack_status(a[71:69]);
    result.header = unpack_header(a[155:72]);
    return result;
  endfunction
endpackage
